### ISSUE TITLE
Layers sometimes appear to be loaded into the map several times

### ISSUE THREAD

**Issue by jessnoo** [Esri/environmental-impact#184]
Seems to be related to the Operational layer/Server config

Characteristics:
- the same feature is drawn several times in the map
- the same feature shows up several times in the pop ups
- the report legend repeats layer symbology

reference configurations:
- with the problem: http://50.18.115.76/EnvImpactUAT/terra/
- without the problem: http://50.18.115.76/EnvImpactUAT/server/

**Comment by CTLocalGovTeam** [comment]
@jessnoo We have fixed this issue and will include in next release

**Comment by NikkiGolding** [comment]
@jessnoo  Please validate

**Comment by jessnoo** [comment]
@CTLocalGovTeam We are still seeing this issue with V1.2.  Please assess our deployment for configuration errors:

http://50.18.115.76/EnvImpact1.2UAT/serverUnderscores 

Please do not take any action until conferring with the Esri team.

**Comment by jessnoo** [comment]
Verified in v1.3
